-- =========================================================
-- CHINOOK SQL BUSINESS ANALYSIS PROJECT
-- =========================================================
-- Project : SQL & Data Querying Internship Project
-- Database : Chinook 
-- Tool:      MySQL Workbench
-- Objective: SQL querying, aggregation & business analysis
-- =========================================================


-- Activate database
USE chinook;


-- =========================================================
-- SECTION 1: CORE SQL ANALYSIS
-- (SELECT | WHERE | ORDER BY | GROUP BY | HAVING | AGGREGATES)
-- =========================================================

-- =========================================================
-- 1. CUSTOMER ANALYSIS
-- =========================================================

-- Retrieve basic customer information
-- Business Insight: Understand customer distribution base
SELECT 
    FirstName,
    LastName,
    Country
FROM customer;


-- Filter customers located in Brazil
-- Business Insight: Identify customers from a specific market segment
SELECT 
    FirstName,
    LastName,
    Country
FROM customer
WHERE Country = 'Brazil';


-- Sort customers alphabetically by last name
-- Business Insight: Improve customer record readability and organization
SELECT 
    FirstName,
    LastName
FROM customer
ORDER BY LastName ASC;


-- Count total number of customers
-- Business Insight: Measure customer base size
SELECT 
    COUNT(*) AS TotalCustomers
FROM customer;


-- =========================================================
-- 2. REVENUE ANALYSIS
-- =========================================================

-- Calculate total revenue generated
-- Business Insight: Overall business performance indicator
SELECT 
    SUM(Total) AS TotalRevenue
FROM invoice;


-- Calculate average invoice value
-- Business Insight: Understand customer spending behavior
SELECT 
    AVG(Total) AS AverageInvoiceValue
FROM invoice;


-- =========================================================
-- 3. REGIONAL PERFORMANCE ANALYSIS
-- =========================================================

-- Revenue generated by each country
-- Business Insight: Identify top-performing markets
SELECT 
    BillingCountry,
    SUM(Total) AS Revenue
FROM invoice
GROUP BY BillingCountry
ORDER BY Revenue DESC;


-- Countries with revenue greater than 100
-- Business Insight: Highlight high-value markets for strategic focus
SELECT 
    BillingCountry,
    SUM(Total) AS Revenue
FROM invoice
GROUP BY BillingCountry
HAVING SUM(Total) > 100
ORDER BY Revenue DESC;




-- =========================================================
-- SECTION 2: ADVANCED SQL QUERIES & ANALYTICS
-- (JOINS | SUBQUERIES | WINDOW FUNCTIONS | OPTIMIZATION)
-- =========================================================


-- =========================================================
-- 1. JOIN OPERATIONS (RELATIONAL ANALYSIS)
-- =========================================================

-- INNER JOIN: Customer Purchase History
-- Business Insight: Link customers to their invoices and spending activity
SELECT 
    c.FirstName,
    c.LastName,
    i.InvoiceDate,
    i.Total
FROM customer c
INNER JOIN invoice i
    ON c.CustomerId = i.CustomerId;


-- LEFT JOIN: Artist Catalogue Coverage
-- Business Insight: Identify all artists, including those without albums
SELECT 
    ar.Name AS ArtistName,
    al.Title AS AlbumTitle
FROM artist ar
LEFT JOIN album al
    ON ar.ArtistId = al.ArtistId;


-- RIGHT JOIN: Complete Artist Coverage Check
-- Business Insight: Ensure no artist is missing from album mapping
SELECT 
    ar.Name AS ArtistName,
    al.Title AS AlbumTitle
FROM album al
RIGHT JOIN artist ar
    ON al.ArtistId = ar.ArtistId;


-- MULTI-TABLE JOIN: Customer Track Purchases
-- Business Insight: Track-level purchasing behavior per customer
SELECT 
    c.FirstName,
    c.LastName,
    t.Name AS TrackName,
    il.Quantity
FROM customer c
INNER JOIN invoice i 
    ON c.CustomerId = i.CustomerId
INNER JOIN invoiceline il 
    ON i.InvoiceId = il.InvoiceId
INNER JOIN track t 
    ON il.TrackId = t.TrackId;


-- =========================================================
-- 2. SUBQUERY ANALYSIS (COMPARATIVE INSIGHTS)
-- =========================================================

-- Customers with above-average total spending
-- Business Insight: Identify high-value customers compared to overall average
SELECT 
    FirstName,
    LastName
FROM customer
WHERE CustomerId IN (
    SELECT CustomerId
    FROM invoice
    GROUP BY CustomerId
    HAVING SUM(Total) > (
        SELECT AVG(Total) FROM invoice
    )
);


-- =========================================================
-- 3. WINDOW FUNCTION ANALYSIS (CUSTOMER RANKING)
-- =========================================================

-- Customer ranking based on total spending (ROW_NUMBER)
-- Business Insight: Unique ranking of customers by revenue contribution
SELECT 
    CustomerId,
    SUM(Total) AS TotalSpent,
    ROW_NUMBER() OVER (ORDER BY SUM(Total) DESC) AS CustomerRank
FROM invoice
GROUP BY CustomerId;


-- Customer ranking (RANK function with ties allowed)
-- Business Insight: Shows tied positions for equal spending customers
SELECT 
    CustomerId,
    SUM(Total) AS TotalSpent,
    RANK() OVER (ORDER BY SUM(Total) DESC) AS CustomerRank
FROM invoice
GROUP BY CustomerId;


-- Country-level customer ranking
-- Business Insight: Compare customer performance within each country
SELECT 
    BillingCountry,
    CustomerId,
    SUM(Total) AS Revenue,
    RANK() OVER (
        PARTITION BY BillingCountry
        ORDER BY SUM(Total) DESC
    ) AS CountryRank
FROM invoice
GROUP BY BillingCountry, CustomerId;


-- =========================================================
-- 4. BUSINESS PERFORMANCE ANALYSIS
-- =========================================================

-- Top 10 highest-spending customers
-- Business Insight: Identify most valuable customers for retention strategy
SELECT 
    c.FirstName,
    c.LastName,
    SUM(i.Total) AS TotalSpent
FROM customer c
INNER JOIN invoice i
    ON c.CustomerId = i.CustomerId
GROUP BY c.CustomerId, c.FirstName, c.LastName
ORDER BY TotalSpent DESC
LIMIT 10;


-- Top 10 best-selling tracks
-- Business Insight: Identify most popular products for marketing focus
SELECT 
    t.Name AS TrackName,
    SUM(il.Quantity) AS TotalSold
FROM track t
INNER JOIN invoiceline il
    ON t.TrackId = il.TrackId
GROUP BY t.TrackId, t.Name
ORDER BY TotalSold DESC
LIMIT 10;


-- Monthly revenue trend analysis
-- Business Insight: Understand business growth patterns over time
SELECT 
    YEAR(InvoiceDate) AS Year,
    MONTH(InvoiceDate) AS Month,
    SUM(Total) AS Revenue
FROM invoice
GROUP BY YEAR(InvoiceDate), MONTH(InvoiceDate)
ORDER BY Year, Month;


-- Customer purchase frequency analysis
-- Business Insight: Measure customer engagement and loyalty
SELECT 
    c.FirstName,
    c.LastName,
    COUNT(i.InvoiceId) AS PurchaseCount
FROM customer c
INNER JOIN invoice i
    ON c.CustomerId = i.CustomerId
GROUP BY c.CustomerId, c.FirstName, c.LastName
ORDER BY PurchaseCount DESC;


-- =========================================================
-- 5. QUERY OPTIMIZATION (INDEXING STRATEGY)
-- =========================================================

-- Purpose: Improve query performance on large datasets

CREATE INDEX idx_invoice_customer
ON invoice(CustomerId);

CREATE INDEX idx_invoiceline_track
ON invoiceline(TrackId);

CREATE INDEX idx_invoice_date
ON invoice(InvoiceDate);


